version: '3.8'

services:
 db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./script/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

 app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
 postgres_data:
